### ISSUE TITLE
VisualBasic CreateLike unable to Arrange String Mock

### ISSUE THREAD

**Issue by andwebz** [telerik/JustMockLite#116]
In a Visual Basic Test Project, I've tried to use the Mock.CreateLike Methode as shown in the [documentation](https://docs.telerik.com/devtools/justmock/basic-usage/create-mocks-by-example), but I am getting an Telerik.JustMock.Core.ElevatedMockingException during Test Execution when setting up a string Property.

The following code can be used to reproduce the problem:

`
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Telerik.JustMock

Namespace UnitTestProject1
    <TestClass>
    Public Class UnitTest1
        <TestMethod>
        Sub TestSub()
            'this works
            Mock.CreateLike(Of IToMock)(Function(x) x.Prop1 = 123)
            Mock.CreateLike(Of IToMock)(Function(x) x.Prop2 = Guid.NewGuid())
            'this does not
            Mock.CreateLike(Of IToMock)(Function(x) x.Prop3 = "value")
        End Sub
    End Class

    Public Interface IToMock
        Property Prop1 As Integer
        Property Prop2 As Guid
        Property Prop3 As String
    End Interface
End Namespace
`

**Comment by mihail-vladov** [comment]
Hi @andwebz,
The expression `x.Prop3 = "value"` will be evaluated to the following: `Operators.CompareString(x.Prop3, "value", False) = 0` by the compiler. To verify this you could use [JustDecompile ](https://www.telerik.com/products/decompiler.aspx)to decompile to output dll. In essence, with this expression, you are trying to arrange the CompareString method which is a static method and this is the reason why you receive the error. If you want to continue using this format of conditional check you should use the commercial version if JustMock which supports mocking everything including static methods.
If you would like to continue using JustMockLite you could change the conditional check to the following: `x.Prop3 Is "value"`.
I hope this information answers your questions.

**Comment by andwebz** [comment]
hi @mihail-vladov ,
using the "Is"-keyword solves my problem, thank you very much.
