### ISSUE TITLE
Performance Issues with JustMock

### ISSUE THREAD

**Issue by JasonBock** [telerik/JustMockLite#162]
I'm currently working on a [PR](https://github.com/ecoAPM/BenchmarkMockNet/pull/21) to add JustMock to the suite of performance tests that currently exist in that repository. The problem is that some of the tests (like `OneParameter` and `Callback`) take a **long** time to finish for JustMock. I'm not sure why, but it's making it such that JustMock can't be added to the test suite. More to the point, the PR can't be accepted as-is because it would take too long to finish.

One thing Steve (owner of the repo) and I talked about is if the `invocationCount` value passed to the `SimpleJobAttribute` (which exists on both the `MockingBenchmark` and `MockingBenchmark<T>` classes) is reduced from 100,000 to something like 1,000, the tests then finish, but that doesn't address the underlying issue why these tests for JustMock slow down over repeated called.

There may be something in the benchmark tests with the way I've set things up with JustMock that may be incorrect. I've never used JustMock until today :). If there's something that I'm doing wrong, please let me know.

**Comment by mihail-vladov** [comment]
Hi Jason,

could you be more specific about the numbers and what you mean by long?
I've downloaded the code from the PR and executed the tests and for OnParameter, JustMock, Moq, and NSubstitue take 1ms to finish. For Callback, JustMock takes 34ms, where Moq and Nsubsitute 10ms and 13ms respectively.
![image](https://user-images.githubusercontent.com/11956739/137497078-4a7bac45-6fa3-476f-bd03-6da87d134741.png)

**Comment by JasonBock** [comment]
FWIW, this also illustrates the issue:
```
using System;
using System.Diagnostics;
using Telerik.JustMock;

for (var iterations = 0; iterations < 5000; iterations++)
{
	var stopwatch = Stopwatch.StartNew();

	for (var i = 0; i < 10; i++)
	{
		var doSomething = Mock.Create<IDoSomething>();
		Mock.Arrange(() => doSomething.Foo());
	}

	stopwatch.Stop();

	Console.WriteLine($"Average time: {(double)stopwatch.ElapsedMilliseconds / 10.0} ms");
}

public interface IDoSomething
{
	void Foo();
}
```
It doesn't have the Benchmark.NET stuff in play. It calls `Arrange()` on an object returned from `Mock.Create()`. When I run this, the average time slowly starts to increase.

No worries on the resolution time. I'm curious to see what you find out :).

**Comment by mihail-vladov** [comment]
Next week I will check again the benchmark application and try to suggest to you how it should be implemented for JustMock.
