### ISSUE TITLE
Any plans to support ASP.NET 5 / DNX (the .NET Execution Environment) ?

### ISSUE THREAD

**Issue by StefH** [telerik/JustMockLite#24]
Any plans to support ASP.NET 5 / DNX (the .NET Execution Environment) ?

Specifically the **dnxcore50** framework.

**Comment by tailsu** [comment]
Does it not work? I'm fairly certain it should work right off the bat.

Or do you have in mind that the JustMock NuGet package doesn't target the DNX frameworks?

**Comment by StefH** [comment]
*Or do you have in mind that the JustMock NuGet package doesn't target the DNX frameworks?* --> **correct**

**Comment by tailsu** [comment]
Can you manually reference the JM library in a DNX project and give it a spin? If it seems to be working I'd be happy to add it to the supported platforms in NuGet.

**Comment by StefH** [comment]
For dnx451 it works, but a dnxcore50 project cannot use JustMock.

See my example projects at : https://github.com/StefH/JustMockTest/tree/master/src
- JustMockTest.dnx451 = **ok**
- JustMockTest.dnxcore50 = **not ok**
- JustMockTest.net45 = **ok**
- JustMockTest.DotNet45 = **ok**
