### ISSUE TITLE
Windows 10 UWP/UAP support

### ISSUE THREAD

**Issue by briandunnington** [telerik/JustMockLite#25]
Attempt #1 (does not work):
Cannot add JustMockLite to a Windows 10 Unit Test project via NuGet because UAP projects are not supported.

Attempt #2 (does not work)
Add reference to Telerik.JustMock.Portable to Windows 10 Unit Test project. This allows the project to compile and run, but any tests using Mock.Create() fail because System.Diagnostics.StackTrace.ctor is not supported.

Just a note: when Visual Studio 2015 was in RC status, we had this working. We simply added a reference to the pre-compiled Telerik.JustMocks assembly and things worked. Updating to VS RTM though broke things. Using the pre-compiled assembly results in a bunch of 'Could not find assembly System.Core v3.5.0.0' exceptions. We tried building from source and retargeting the framework to 4, 4.5, 4.5.2, and 4.6, but when we build it ourselves and try to reference the binary, VS complains that the Win10 Unit Test project is of type NetCore and the JustMock assembly targets NetFramework.

Any plans to support Windows 10 UWP/UAP projects?

**Comment by tailsu** [comment]
I did some research on the topic.

It will be a pretty big effort to get to run JustMock (with dynamically generated mocks and the auto-mocking container0 on NetCore - not impossible, but not trivial. I can't give an estimate when that can be done. I've logged the issue in our backlog.

It would be much easier to get JustMock Portable to run on NetCore, but the way it works is very different from the non-portable one and it doesn't have all the features.

For the time being, I'll check if I can clear the StackTrace problem with the portable version and see what's necessary to get it to work.

**Comment by briandunnington** [comment]
Thanks for the update. For what it is worth, it was working for UWP apps when VS2015 was in RC status. But when they released the RTM version, it stopped working. Not sure why/how it was working previously (maybe the API surface changed in the updated UWP SDK) but it was super handy when it was working.

**Comment by japf** [comment]
Looking forward seeing UWP support too :-)

**Comment by tailsu** [comment]
It worked in RC because the unit test project template from RC targeted the desktop framework.

**Comment by dachibox** [comment]
Waiting for the Universal Windows Class Library support too. Would be available soon?

**Comment by mihail-vladov** [comment]
I will close this as it is a bit old now. If you have any questions, please open a new issue.
