### ISSUE TITLE
Referencing nuget package from UnitTestLibrary(Windows Store) not working

### ISSUE THREAD

**Issue by corcus** [telerik/JustMockLite#26]
Hi, 
I am trying to reference the Just Mock nuget package from a Unit Test Library targeting Windows 8.1 as it is described in the How To section [here](http://www.telerik.com/help/justmock/advanced-usage-mocking-inside-winrt.html). 

The error I am getting is this: Could not install package 'JustMock 2016.1.107.7'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Visual Studio Pro 2015. 

Could you please point out what I am doing wrong?
Thanks in advance for any help

**Comment by tailsu** [comment]
I think that's a VS bug. Did you try adding a reference to `Telerik.JustMock` to your test project manually?

**Comment by corcus** [comment]
Hi again,
I tried building the solution per the instructions here and adding a reference to Telerik.JustMock.dll found in the Binaries Folder(I used DebugFree configuration).
Now the error is this : C:\xxx\Binaries\DebugFree\Telerik.JustMock.dll could not be added. The project targets '.NetCore' while the file reference targets '.NetFramework'. This is not a supported scenario. 

Maybe this is a Visual Studio 2015 issue.

**Comment by tailsu** [comment]
Mind you, regular JustMock works for Windows Store apps only when they run in the desktop test runner. Running on WinRT-only devices is supported only by JustMock for Devices (JM4D).

I did the following and it worked:
* create a Store Apps->Windows Apps->Unit Test Library (Windows)
* unload the project and open it for editing
* add the reference to JustMock manually
* save and reload
* build and run the test - it works

I admit that the experience is pretty painful and wince-worthy, but that's the way it is now. 

This is what the relevant part of my project looks like:

```
  <ItemGroup>
     <!--A reference to the entire .Net Framework and Windows SDK are automatically included--> 
    <SDKReference Include="MSTestFramework, Version=11.0" />
    <SDKReference Include="TestPlatform, Version=11.0" />
    <Reference Include="Telerik.JustMock">
      <HintPath>D:\Projects\MATTeam\JustMock\Binaries\Debug\Telerik.JustMock.dll</HintPath>
    </Reference>
  </ItemGroup>
```

If you do the same, you will be able to run Windows Store tests on the desktop, no problem.

**Comment by corcus** [comment]
Thanks a lot. It works for me now too.
