### ISSUE TITLE
TestFixtureSetUpAttribute and TestFixtureTearDownAttribute not found

### ISSUE THREAD

**Issue by VansFannel** [telerik/JustMockLite#29]
I'm developing a TDD test with C#, .NET Framework 4.7, Nunit 3.8.0 and JustMock Lite 2017.2.821.1.

When I do:

`IGenericRepository<ProductionOrder> _proOrdRepository = 
                Mock.Create<IGenericRepository<ProductionOrder>>();`

I get this message:

> System.TypeInitializationException occurred
>   HResult=0x80131534
>   Message=An exception occurred in the type initializer of 'Telerik.JustMock.Core.Context.MockingContext'.
>   Source=Telerik.JustMock
>   StackTrace:
>    at Telerik.JustMock.Core.Context.MockingContext.get_CurrentRepository()
>    at Telerik.JustMock.Mock.<>c__441.<Create>b__44_0()
>    at Telerik.JustMock.Core.ProfilerInterceptor.GuardInternal[T](Func`1 guardedAction)
>    at Telerik.JustMock.Mock.Create[T]()
>    at InvesControl.Trazabilidad.TRZL.ImportBatch.Tests.LoadFinishedTrzlBatchTest.SetUpLoadFinishedTrzlBatch() in D:\MyProjects\MyProject\LoadFinishedTrzlBatchTest.cs:line 25
> 
> Inner Exception 1:
> InvalidOperationException: Some attribute type among NUnit.Framework.TestFixtureSetUpAttribute, nunit.framework,NUnit.Framework.TestFixtureTearDownAttribute, nunit.framework not found.

I think that the problem is that JustMock doesn't support NUnit 3.8.0.

**Comment by rprouse** [comment]
`TestFixtureSetUpAttribute` and `TestFixtureTearDownAttribute` were deprecated in NUnit 3.0 several years ago and removed in NUnit 3.8. The attributes should be replaced by `OneTimeSetUpAttribute` and `OneTimeTearDownAttribute` for NUnit 3+.

**Comment by VansFannel** [comment]
I solved this problem using NUnit 3.7.1 instead of 3.8.0, so the error is in JustMockLite.

**Comment by tailsu** [comment]
Looks like a bug at this line
https://github.com/telerik/JustMockLite/blob/master/Telerik.JustMock/Core/Context/NUnitMockingContextResolver.cs#L63

**Comment by mihail-vladov** [comment]
Hi guys,
We are currently working on a fix. I will write back once the fix is available.

**Comment by k3flo** [comment]
The issue is still there... When will it be fixed?

**Comment by mihail-vladov** [comment]
We have just released an internal build which includes a fix for the missing attributes. Feel free to give it a try and get back to us if you encounter any issues.

**Comment by sasonar** [comment]
Is this ever got fixed?

**Comment by mihail-vladov** [comment]
Hi Sesonar, the problem is already fixed with the R1 2018 release and of course, is available in all subsequent releases.

**Comment by guptavt** [comment]
so which version of NUnit i should download?
