### ISSUE TITLE
MockingContainer<T> is missing the ArrangeSet/AssertSet methods.

### ISSUE THREAD

**Issue by tailsu** [telerik/JustMockLite#83]
Just like the core mocking API has ArrangeSet/AssertSet methods, so should the MockingContainer have them.

I'm not sure what caused this oversight.

**Comment by mihail-vladov** [comment]
Hi Stefan,
Thank you for the suggestion. I am marking this as a feature request.

**Comment by mihail-vladov** [comment]
The implementation of this feature is available with R1 2020 release (2020.1.113.1).
